### ISSUE TITLE
GC76EBRROA6DWMCCVPZZYHU3HHNOBHHTGFQYEOEVQLWHVDCDC5YJZ5QK

### ISSUE THREAD

**Issue by piposan** [orbitlens/stellar-expert-explorer#199] opened 2020-06-01 11:27 UTC
Hi there, looking to retrieve an old wallet history but seems it's no longer available on the explorer. I think I may have also still had some Mobi stored in this wallet too!

**Comment by orbitlens** [comment] 2020-06-02 04:52
The account you mentioned never existed on the ledger. It means it didn't have any funds on it, nor the transactions history. Maybe you generated new keypair a while ago, but forgot to fund it (which is required to create the account on the Stellar network).

**Comment by piposan** [comment] 2020-06-02 08:16
If that was the case then how come another account I hold has transactions from that address as shown ? Also seem to have 6,000 Mobi missing without any apparent withdrawal
!

[Screen Shot 2020-06-02 at 09 15 15](https://user-images.githubusercontent.com/29426190/83496905-a6091080-a4b1-11ea-930f-9d4fbf205c48.png)
![Screen Shot 2020-06-02 at 09 14 44](https://user-images.githubusercontent.com/29426190/83496918-a99c9780-a4b1-11ea-9d48-7ce0dafc22cf.png)
![Screen Shot 2020-06-02 at 09 13 19](https://user-images.githubusercontent.com/29426190/83496928-ad301e80-a4b1-11ea-94e1-d367cbff338f.png)
![Screen Shot 2020-06-02 at 09 12 53](https://user-images.githubusercontent.com/29426190/83496937-af927880-a4b1-11ea-8c1f-c5733441751b.png)



 from my account

**Comment by orbitlens** [comment] 2020-06-02 22:12
Yes, you are right. I didn't check everything thoroughly enough. Sorry about that.

The account [GC76...Z5QK](https://stellar.expert/explorer/public/account/GC76EBRROA6DWMCCVPZZYHU3HHNOBHHTGFQYEOEVQLWHVDCDC5YJZ5QK) has been merged back in 2018. It means that all funds have been transferred to another account (judging from the description provided in transaction memo, funds were transferred to [this](https://stellar.expert/explorer/public/account/GCQPMNEVAEU5OH6XRF3GGZS2KNN5BT3MIPMOMJAM7B2UAK3CTGLOF5YN) Ledger wallet) and then GC76...Z5QK was deleted from the network. 

StellarExpert shows all operations even for deleted accounts, but in this particular case our server returned an error caused by the side-effect of new account activity metrics that we introduced a few weeks ago. We rolled out a hotfix for this issue, and now everything is back to normal.

As for your second question, looks like you bought 6000 MOBI tokens using account [GDOL...URDF](https://stellar.expert/explorer/public/account/GDOLRT5JUV5XYIOGSEHC3ELVAY25S4EM7UKG63OPEGTO6TNIYYDWURDF) and then transferred all of them to [GCQP...F5YN](https://stellar.expert/explorer/public/account/GCQPMNEVAEU5OH6XRF3GGZS2KNN5BT3MIPMOMJAM7B2UAK3CTGLOF5YN?filter=trades) and later on sold all of them for XLM (see trades history for this account [here](https://stellar.expert/explorer/public/account/GCQPMNEVAEU5OH6XRF3GGZS2KNN5BT3MIPMOMJAM7B2UAK3CTGLOF5YN?filter=trades)).

Again, sorry for the inconvenience.

**Closed by orbitlens** 2020-06-02 22:12 UTC
Labels: bug, question
