### ISSUE TITLE
Keep getting unable to render on stellar.expert

### ISSUE THREAD

**Issue by dob-im** [orbitlens/stellar-expert-explorer#344] opened 2021-02-05 18:29 UTC
I am trying to find out why this error is occurring when trying to view this address:
https://stellar.expert/explorer/public/account/GA5QQMLTO6FM6ZRO4QGX266LSLNRO6THGH5WRJUITLOJVEVY35BVDOBC

![image](https://user-images.githubusercontent.com/78550508/107073800-d11cd000-67b5-11eb-8f9e-122995ef37d9.png)

The same appears correctly without error here:
https://stellarchain.io/address/GA5QQMLTO6FM6ZRO4QGX266LSLNRO6THGH5WRJUITLOJVEVY35BVDOBC

**Comment by orbitlens** [comment] 2021-02-05 22:45
The problem was caused by missing `stellar.toml` on the account `home_domain`.
Fixed in v0.15.20.

**Closed by orbitlens** 2021-02-05 22:45 UTC
Labels: bug
