### ISSUE TITLE
Stellar Expert  Unhandled Error for Asset PAYBO

### ISSUE THREAD

**Issue by paybookclub** [orbitlens/stellar-expert-explorer#275] opened 2020-12-29 11:52 UTC
Unhandled error occurred
"fffff" at https://stellar.expert/explorer/public/asset/PAYBO-GDNUDY5LNUVCO55LLK6H2RCOILB6EO7UOVAOGDTV3FB7Y2U45TMAXD3D-2?filter=payments&term=PAYBO
Error: fffff
    at De (https://stellar.expert/distr/explorer.js:1:147836)
    at Zi (https://stellar.expert/distr/app.js?v=0.15.9:2:521759)
    at Es (https://stellar.expert/distr/app.js?v=0.15.9:2:567809)
    at yu (https://stellar.expert/distr/app.js?v=0.15.9:2:560551)
    at mu (https://stellar.expert/distr/app.js?v=0.15.9:2:560476)
    at su (https://stellar.expert/distr/app.js?v=0.15.9:2:557506)
    at https://stellar.expert/distr/app.js?v=0.15.9:2:509147
    at t.unstable_runWithPriority (https://stellar.expert/distr/app.js?v=0.15.9:2:584203)
    at Qo (https://stellar.expert/distr/app.js?v=0.15.9:2:508856)
    at Yo (https://stellar.expert/distr/app.js?v=0.15.9:2:509092)
If this error persists please contact our support.

**Comment by theclabs** [comment] 2020-12-29 11:57
Duplicate of #274 -

**Comment by orbitlens** [comment] 2020-12-29 14:18
Sorry about that, guys. The system update we rolled recently gone wrong.
Fixed now.

**Closed by orbitlens** 2020-12-29 14:18 UTC
Labels: bug
